
user/_test:     file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <main>:
#include "include/types.h"
#include "include/user.h"
int main(int argc, char *argv[]){
   0:	1141                	add	sp,sp,-16
   2:	e406                	sd	ra,8(sp)
   4:	e022                	sd	s0,0(sp)
   6:	0800                	add	s0,sp,16
    hello();
   8:	01e000ef          	jal	26 <hello>
    return 0;
   c:	4501                	li	a0,0
   e:	60a2                	ld	ra,8(sp)
  10:	6402                	ld	s0,0(sp)
  12:	0141                	add	sp,sp,16
  14:	8082                	ret

0000000000000016 <start>:
#include "include/user.h"


void
start(int argc, char **argv)
{
  16:	1141                	add	sp,sp,-16
  18:	e406                	sd	ra,8(sp)
  1a:	e022                	sd	s0,0(sp)
  1c:	0800                	add	s0,sp,16
  int r;
  extern int main(int argc, char **argv);
  r = main(argc, argv);
  1e:	fe3ff0ef          	jal	0 <main>


  exit(r);
  22:	00c000ef          	jal	2e <exit>

0000000000000026 <hello>:
# generated by usys.pl - do not edit
#include "include/syscall.h"
.global hello
hello:
 li a7, SYS_hello
  26:	4885                	li	a7,1
 ecall
  28:	00000073          	ecall
 ret
  2c:	8082                	ret

000000000000002e <exit>:
.global exit
exit:
 li a7, SYS_exit
  2e:	4889                	li	a7,2
 ecall
  30:	00000073          	ecall
 ret
  34:	8082                	ret

0000000000000036 <fork>:
.global fork
fork:
 li a7, SYS_fork
  36:	4891                	li	a7,4
 ecall
  38:	00000073          	ecall
 ret
  3c:	8082                	ret

000000000000003e <wait>:
.global wait
wait:
 li a7, SYS_wait
  3e:	488d                	li	a7,3
 ecall
  40:	00000073          	ecall
 ret
  44:	8082                	ret

0000000000000046 <exec>:
.global exec
exec:
 li a7, SYS_exec
  46:	4895                	li	a7,5
 ecall
  48:	00000073          	ecall
 ret
  4c:	8082                	ret

000000000000004e <dup>:
.global dup
dup:
 li a7, SYS_dup
  4e:	489d                	li	a7,7
 ecall
  50:	00000073          	ecall
 ret
  54:	8082                	ret

0000000000000056 <open>:
.global open
open:
 li a7, SYS_open
  56:	4899                	li	a7,6
 ecall
  58:	00000073          	ecall
 ret
  5c:	8082                	ret

000000000000005e <mknod>:
.global mknod
mknod:
 li a7, SYS_mknod
  5e:	48a1                	li	a7,8
 ecall
  60:	00000073          	ecall
 ret
  64:	8082                	ret

0000000000000066 <write>:
.global write
write:
 li a7, SYS_write
  66:	48a5                	li	a7,9
 ecall
  68:	00000073          	ecall
 ret
  6c:	8082                	ret

000000000000006e <read>:
.global read
read:
 li a7, SYS_read
  6e:	48a9                	li	a7,10
 ecall
  70:	00000073          	ecall
 ret
  74:	8082                	ret

0000000000000076 <close>:
.global close
close:
 li a7, SYS_close
  76:	48ad                	li	a7,11
 ecall
  78:	00000073          	ecall
 ret
  7c:	8082                	ret

000000000000007e <getpid>:
.global getpid
getpid:
 li a7, SYS_getpid
  7e:	48b1                	li	a7,12
 ecall
  80:	00000073          	ecall
 ret
  84:	8082                	ret

0000000000000086 <unlink>:
.global unlink
unlink:
 li a7, SYS_unlink
  86:	48b5                	li	a7,13
 ecall
  88:	00000073          	ecall
 ret
  8c:	8082                	ret

000000000000008e <putc>:

static char digits[] = "0123456789ABCDEF";

static void
putc(int fd, char c)
{
  8e:	1101                	add	sp,sp,-32
  90:	ec06                	sd	ra,24(sp)
  92:	e822                	sd	s0,16(sp)
  94:	1000                	add	s0,sp,32
  96:	feb407a3          	sb	a1,-17(s0)
  write(fd, &c, 1);
  9a:	4605                	li	a2,1
  9c:	fef40593          	add	a1,s0,-17
  a0:	fc7ff0ef          	jal	66 <write>
}
  a4:	60e2                	ld	ra,24(sp)
  a6:	6442                	ld	s0,16(sp)
  a8:	6105                	add	sp,sp,32
  aa:	8082                	ret

00000000000000ac <printint>:

static void
printint(int fd, long long xx, int base, int sgn)
{
  ac:	715d                	add	sp,sp,-80
  ae:	e486                	sd	ra,72(sp)
  b0:	e0a2                	sd	s0,64(sp)
  b2:	fc26                	sd	s1,56(sp)
  b4:	f84a                	sd	s2,48(sp)
  b6:	f44e                	sd	s3,40(sp)
  b8:	0880                	add	s0,sp,80
  ba:	892a                	mv	s2,a0
  char buf[20];
  int i, neg;
  unsigned long long x;

  neg = 0;
  if(sgn && xx < 0){
  bc:	c299                	beqz	a3,c2 <printint+0x16>
  be:	0605cf63          	bltz	a1,13c <printint+0x90>
  neg = 0;
  c2:	4881                	li	a7,0
  c4:	fb840693          	add	a3,s0,-72
    x = -xx;
  } else {
    x = xx;
  }

  i = 0;
  c8:	4781                	li	a5,0
  do{
    buf[i++] = digits[x % base];
  ca:	45800513          	li	a0,1112
  ce:	883e                	mv	a6,a5
  d0:	2785                	addw	a5,a5,1
  d2:	02c5f733          	remu	a4,a1,a2
  d6:	972a                	add	a4,a4,a0
  d8:	00074703          	lbu	a4,0(a4)
  dc:	00e68023          	sb	a4,0(a3)
  }while((x /= base) != 0);
  e0:	872e                	mv	a4,a1
  e2:	02c5d5b3          	divu	a1,a1,a2
  e6:	0685                	add	a3,a3,1
  e8:	fec773e3          	bgeu	a4,a2,ce <printint+0x22>
  if(neg)
  ec:	00088b63          	beqz	a7,102 <printint+0x56>
    buf[i++] = '-';
  f0:	fd078793          	add	a5,a5,-48
  f4:	97a2                	add	a5,a5,s0
  f6:	02d00713          	li	a4,45
  fa:	fee78423          	sb	a4,-24(a5)
  fe:	0028079b          	addw	a5,a6,2

  while(--i >= 0)
 102:	02f05663          	blez	a5,12e <printint+0x82>
 106:	fb840713          	add	a4,s0,-72
 10a:	00f704b3          	add	s1,a4,a5
 10e:	fff70993          	add	s3,a4,-1
 112:	99be                	add	s3,s3,a5
 114:	37fd                	addw	a5,a5,-1
 116:	1782                	sll	a5,a5,0x20
 118:	9381                	srl	a5,a5,0x20
 11a:	40f989b3          	sub	s3,s3,a5
    putc(fd, buf[i]);
 11e:	fff4c583          	lbu	a1,-1(s1)
 122:	854a                	mv	a0,s2
 124:	f6bff0ef          	jal	8e <putc>
  while(--i >= 0)
 128:	14fd                	add	s1,s1,-1
 12a:	ff349ae3          	bne	s1,s3,11e <printint+0x72>
}
 12e:	60a6                	ld	ra,72(sp)
 130:	6406                	ld	s0,64(sp)
 132:	74e2                	ld	s1,56(sp)
 134:	7942                	ld	s2,48(sp)
 136:	79a2                	ld	s3,40(sp)
 138:	6161                	add	sp,sp,80
 13a:	8082                	ret
    x = -xx;
 13c:	40b005b3          	neg	a1,a1
    neg = 1;
 140:	4885                	li	a7,1
    x = -xx;
 142:	b749                	j	c4 <printint+0x18>

0000000000000144 <vprintf>:
}

// Print to the given fd. Only understands %d, %x, %p, %c, %s.
void
vprintf(int fd, const char *fmt, va_list ap)
{
 144:	711d                	add	sp,sp,-96
 146:	ec86                	sd	ra,88(sp)
 148:	e8a2                	sd	s0,80(sp)
 14a:	e4a6                	sd	s1,72(sp)
 14c:	e0ca                	sd	s2,64(sp)
 14e:	fc4e                	sd	s3,56(sp)
 150:	f852                	sd	s4,48(sp)
 152:	f456                	sd	s5,40(sp)
 154:	f05a                	sd	s6,32(sp)
 156:	ec5e                	sd	s7,24(sp)
 158:	e862                	sd	s8,16(sp)
 15a:	e466                	sd	s9,8(sp)
 15c:	e06a                	sd	s10,0(sp)
 15e:	1080                	add	s0,sp,96
  char *s;
  int c0, c1, c2, i, state;

  state = 0;
  for(i = 0; fmt[i]; i++){
 160:	0005c903          	lbu	s2,0(a1)
 164:	26090363          	beqz	s2,3ca <vprintf+0x286>
 168:	8b2a                	mv	s6,a0
 16a:	8a2e                	mv	s4,a1
 16c:	8bb2                	mv	s7,a2
  state = 0;
 16e:	4981                	li	s3,0
  for(i = 0; fmt[i]; i++){
 170:	4481                	li	s1,0
 172:	4701                	li	a4,0
      if(c0 == '%'){
        state = '%';
      } else {
        putc(fd, c0);
      }
    } else if(state == '%'){
 174:	02500a93          	li	s5,37
      c1 = c2 = 0;
      if(c0) c1 = fmt[i+1] & 0xff;
      if(c1) c2 = fmt[i+2] & 0xff;
      if(c0 == 'd'){
 178:	06400c13          	li	s8,100
        printint(fd, va_arg(ap, int), 10, 1);
      } else if(c0 == 'l' && c1 == 'd'){
 17c:	06c00c93          	li	s9,108
 180:	a005                	j	1a0 <vprintf+0x5c>
        putc(fd, c0);
 182:	85ca                	mv	a1,s2
 184:	855a                	mv	a0,s6
 186:	f09ff0ef          	jal	8e <putc>
 18a:	a019                	j	190 <vprintf+0x4c>
    } else if(state == '%'){
 18c:	03598263          	beq	s3,s5,1b0 <vprintf+0x6c>
  for(i = 0; fmt[i]; i++){
 190:	2485                	addw	s1,s1,1
 192:	8726                	mv	a4,s1
 194:	009a07b3          	add	a5,s4,s1
 198:	0007c903          	lbu	s2,0(a5)
 19c:	22090763          	beqz	s2,3ca <vprintf+0x286>
    c0 = fmt[i] & 0xff;
 1a0:	0009079b          	sext.w	a5,s2
    if(state == 0){
 1a4:	fe0994e3          	bnez	s3,18c <vprintf+0x48>
      if(c0 == '%'){
 1a8:	fd579de3          	bne	a5,s5,182 <vprintf+0x3e>
        state = '%';
 1ac:	89be                	mv	s3,a5
 1ae:	b7cd                	j	190 <vprintf+0x4c>
      if(c0) c1 = fmt[i+1] & 0xff;
 1b0:	cbc9                	beqz	a5,242 <vprintf+0xfe>
 1b2:	00ea06b3          	add	a3,s4,a4
 1b6:	0016c683          	lbu	a3,1(a3)
      c1 = c2 = 0;
 1ba:	8636                	mv	a2,a3
      if(c1) c2 = fmt[i+2] & 0xff;
 1bc:	c681                	beqz	a3,1c4 <vprintf+0x80>
 1be:	9752                	add	a4,a4,s4
 1c0:	00274603          	lbu	a2,2(a4)
      if(c0 == 'd'){
 1c4:	05878363          	beq	a5,s8,20a <vprintf+0xc6>
      } else if(c0 == 'l' && c1 == 'd'){
 1c8:	05978d63          	beq	a5,s9,222 <vprintf+0xde>
        printint(fd, va_arg(ap, uint64), 10, 1);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
        printint(fd, va_arg(ap, uint64), 10, 1);
        i += 2;
      } else if(c0 == 'u'){
 1cc:	07500713          	li	a4,117
 1d0:	0ee78763          	beq	a5,a4,2be <vprintf+0x17a>
        printint(fd, va_arg(ap, uint64), 10, 0);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'u'){
        printint(fd, va_arg(ap, uint64), 10, 0);
        i += 2;
      } else if(c0 == 'x'){
 1d4:	07800713          	li	a4,120
 1d8:	12e78963          	beq	a5,a4,30a <vprintf+0x1c6>
        printint(fd, va_arg(ap, uint64), 16, 0);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'x'){
        printint(fd, va_arg(ap, uint64), 16, 0);
        i += 2;
      } else if(c0 == 'p'){
 1dc:	07000713          	li	a4,112
 1e0:	14e78e63          	beq	a5,a4,33c <vprintf+0x1f8>
        printptr(fd, va_arg(ap, uint64));
      } else if(c0 == 'c'){
 1e4:	06300713          	li	a4,99
 1e8:	18e78a63          	beq	a5,a4,37c <vprintf+0x238>
        putc(fd, va_arg(ap, uint32));
      } else if(c0 == 's'){
 1ec:	07300713          	li	a4,115
 1f0:	1ae78063          	beq	a5,a4,390 <vprintf+0x24c>
        if((s = va_arg(ap, char*)) == 0)
          s = "(null)";
        for(; *s; s++)
          putc(fd, *s);
      } else if(c0 == '%'){
 1f4:	02500713          	li	a4,37
 1f8:	04e79563          	bne	a5,a4,242 <vprintf+0xfe>
        putc(fd, '%');
 1fc:	02500593          	li	a1,37
 200:	855a                	mv	a0,s6
 202:	e8dff0ef          	jal	8e <putc>
        // Unknown % sequence.  Print it to draw attention.
        putc(fd, '%');
        putc(fd, c0);
      }

      state = 0;
 206:	4981                	li	s3,0
 208:	b761                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, int), 10, 1);
 20a:	008b8913          	add	s2,s7,8
 20e:	4685                	li	a3,1
 210:	4629                	li	a2,10
 212:	000ba583          	lw	a1,0(s7)
 216:	855a                	mv	a0,s6
 218:	e95ff0ef          	jal	ac <printint>
 21c:	8bca                	mv	s7,s2
      state = 0;
 21e:	4981                	li	s3,0
 220:	bf85                	j	190 <vprintf+0x4c>
      } else if(c0 == 'l' && c1 == 'd'){
 222:	06400793          	li	a5,100
 226:	02f68963          	beq	a3,a5,258 <vprintf+0x114>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
 22a:	06c00793          	li	a5,108
 22e:	04f68263          	beq	a3,a5,272 <vprintf+0x12e>
      } else if(c0 == 'l' && c1 == 'u'){
 232:	07500793          	li	a5,117
 236:	0af68063          	beq	a3,a5,2d6 <vprintf+0x192>
      } else if(c0 == 'l' && c1 == 'x'){
 23a:	07800793          	li	a5,120
 23e:	0ef68263          	beq	a3,a5,322 <vprintf+0x1de>
        putc(fd, '%');
 242:	02500593          	li	a1,37
 246:	855a                	mv	a0,s6
 248:	e47ff0ef          	jal	8e <putc>
        putc(fd, c0);
 24c:	85ca                	mv	a1,s2
 24e:	855a                	mv	a0,s6
 250:	e3fff0ef          	jal	8e <putc>
      state = 0;
 254:	4981                	li	s3,0
 256:	bf2d                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 1);
 258:	008b8913          	add	s2,s7,8
 25c:	4685                	li	a3,1
 25e:	4629                	li	a2,10
 260:	000bb583          	ld	a1,0(s7)
 264:	855a                	mv	a0,s6
 266:	e47ff0ef          	jal	ac <printint>
        i += 1;
 26a:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 10, 1);
 26c:	8bca                	mv	s7,s2
      state = 0;
 26e:	4981                	li	s3,0
        i += 1;
 270:	b705                	j	190 <vprintf+0x4c>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
 272:	06400793          	li	a5,100
 276:	02f60763          	beq	a2,a5,2a4 <vprintf+0x160>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'u'){
 27a:	07500793          	li	a5,117
 27e:	06f60963          	beq	a2,a5,2f0 <vprintf+0x1ac>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'x'){
 282:	07800793          	li	a5,120
 286:	faf61ee3          	bne	a2,a5,242 <vprintf+0xfe>
        printint(fd, va_arg(ap, uint64), 16, 0);
 28a:	008b8913          	add	s2,s7,8
 28e:	4681                	li	a3,0
 290:	4641                	li	a2,16
 292:	000bb583          	ld	a1,0(s7)
 296:	855a                	mv	a0,s6
 298:	e15ff0ef          	jal	ac <printint>
        i += 2;
 29c:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 16, 0);
 29e:	8bca                	mv	s7,s2
      state = 0;
 2a0:	4981                	li	s3,0
        i += 2;
 2a2:	b5fd                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 1);
 2a4:	008b8913          	add	s2,s7,8
 2a8:	4685                	li	a3,1
 2aa:	4629                	li	a2,10
 2ac:	000bb583          	ld	a1,0(s7)
 2b0:	855a                	mv	a0,s6
 2b2:	dfbff0ef          	jal	ac <printint>
        i += 2;
 2b6:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 10, 1);
 2b8:	8bca                	mv	s7,s2
      state = 0;
 2ba:	4981                	li	s3,0
        i += 2;
 2bc:	bdd1                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint32), 10, 0);
 2be:	008b8913          	add	s2,s7,8
 2c2:	4681                	li	a3,0
 2c4:	4629                	li	a2,10
 2c6:	000be583          	lwu	a1,0(s7)
 2ca:	855a                	mv	a0,s6
 2cc:	de1ff0ef          	jal	ac <printint>
 2d0:	8bca                	mv	s7,s2
      state = 0;
 2d2:	4981                	li	s3,0
 2d4:	bd75                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 0);
 2d6:	008b8913          	add	s2,s7,8
 2da:	4681                	li	a3,0
 2dc:	4629                	li	a2,10
 2de:	000bb583          	ld	a1,0(s7)
 2e2:	855a                	mv	a0,s6
 2e4:	dc9ff0ef          	jal	ac <printint>
        i += 1;
 2e8:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 10, 0);
 2ea:	8bca                	mv	s7,s2
      state = 0;
 2ec:	4981                	li	s3,0
        i += 1;
 2ee:	b54d                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 0);
 2f0:	008b8913          	add	s2,s7,8
 2f4:	4681                	li	a3,0
 2f6:	4629                	li	a2,10
 2f8:	000bb583          	ld	a1,0(s7)
 2fc:	855a                	mv	a0,s6
 2fe:	dafff0ef          	jal	ac <printint>
        i += 2;
 302:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 10, 0);
 304:	8bca                	mv	s7,s2
      state = 0;
 306:	4981                	li	s3,0
        i += 2;
 308:	b561                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint32), 16, 0);
 30a:	008b8913          	add	s2,s7,8
 30e:	4681                	li	a3,0
 310:	4641                	li	a2,16
 312:	000be583          	lwu	a1,0(s7)
 316:	855a                	mv	a0,s6
 318:	d95ff0ef          	jal	ac <printint>
 31c:	8bca                	mv	s7,s2
      state = 0;
 31e:	4981                	li	s3,0
 320:	bd85                	j	190 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 16, 0);
 322:	008b8913          	add	s2,s7,8
 326:	4681                	li	a3,0
 328:	4641                	li	a2,16
 32a:	000bb583          	ld	a1,0(s7)
 32e:	855a                	mv	a0,s6
 330:	d7dff0ef          	jal	ac <printint>
        i += 1;
 334:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 16, 0);
 336:	8bca                	mv	s7,s2
      state = 0;
 338:	4981                	li	s3,0
        i += 1;
 33a:	bd99                	j	190 <vprintf+0x4c>
        printptr(fd, va_arg(ap, uint64));
 33c:	008b8d13          	add	s10,s7,8
 340:	000bb983          	ld	s3,0(s7)
  putc(fd, '0');
 344:	03000593          	li	a1,48
 348:	855a                	mv	a0,s6
 34a:	d45ff0ef          	jal	8e <putc>
  putc(fd, 'x');
 34e:	07800593          	li	a1,120
 352:	855a                	mv	a0,s6
 354:	d3bff0ef          	jal	8e <putc>
 358:	4941                	li	s2,16
    putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 35a:	45800b93          	li	s7,1112
 35e:	03c9d793          	srl	a5,s3,0x3c
 362:	97de                	add	a5,a5,s7
 364:	0007c583          	lbu	a1,0(a5)
 368:	855a                	mv	a0,s6
 36a:	d25ff0ef          	jal	8e <putc>
  for (i = 0; i < (sizeof(uint64) * 2); i++, x <<= 4)
 36e:	0992                	sll	s3,s3,0x4
 370:	397d                	addw	s2,s2,-1
 372:	fe0916e3          	bnez	s2,35e <vprintf+0x21a>
        printptr(fd, va_arg(ap, uint64));
 376:	8bea                	mv	s7,s10
      state = 0;
 378:	4981                	li	s3,0
 37a:	bd19                	j	190 <vprintf+0x4c>
        putc(fd, va_arg(ap, uint32));
 37c:	008b8913          	add	s2,s7,8
 380:	000bc583          	lbu	a1,0(s7)
 384:	855a                	mv	a0,s6
 386:	d09ff0ef          	jal	8e <putc>
 38a:	8bca                	mv	s7,s2
      state = 0;
 38c:	4981                	li	s3,0
 38e:	b509                	j	190 <vprintf+0x4c>
        if((s = va_arg(ap, char*)) == 0)
 390:	008b8993          	add	s3,s7,8
 394:	000bb903          	ld	s2,0(s7)
 398:	00090f63          	beqz	s2,3b6 <vprintf+0x272>
        for(; *s; s++)
 39c:	00094583          	lbu	a1,0(s2)
 3a0:	c195                	beqz	a1,3c4 <vprintf+0x280>
          putc(fd, *s);
 3a2:	855a                	mv	a0,s6
 3a4:	cebff0ef          	jal	8e <putc>
        for(; *s; s++)
 3a8:	0905                	add	s2,s2,1
 3aa:	00094583          	lbu	a1,0(s2)
 3ae:	f9f5                	bnez	a1,3a2 <vprintf+0x25e>
        if((s = va_arg(ap, char*)) == 0)
 3b0:	8bce                	mv	s7,s3
      state = 0;
 3b2:	4981                	li	s3,0
 3b4:	bbf1                	j	190 <vprintf+0x4c>
          s = "(null)";
 3b6:	00000917          	auipc	s2,0x0
 3ba:	09a90913          	add	s2,s2,154 # 450 <printf+0x40>
        for(; *s; s++)
 3be:	02800593          	li	a1,40
 3c2:	b7c5                	j	3a2 <vprintf+0x25e>
        if((s = va_arg(ap, char*)) == 0)
 3c4:	8bce                	mv	s7,s3
      state = 0;
 3c6:	4981                	li	s3,0
 3c8:	b3e1                	j	190 <vprintf+0x4c>
    }
  }
}
 3ca:	60e6                	ld	ra,88(sp)
 3cc:	6446                	ld	s0,80(sp)
 3ce:	64a6                	ld	s1,72(sp)
 3d0:	6906                	ld	s2,64(sp)
 3d2:	79e2                	ld	s3,56(sp)
 3d4:	7a42                	ld	s4,48(sp)
 3d6:	7aa2                	ld	s5,40(sp)
 3d8:	7b02                	ld	s6,32(sp)
 3da:	6be2                	ld	s7,24(sp)
 3dc:	6c42                	ld	s8,16(sp)
 3de:	6ca2                	ld	s9,8(sp)
 3e0:	6d02                	ld	s10,0(sp)
 3e2:	6125                	add	sp,sp,96
 3e4:	8082                	ret

00000000000003e6 <fprintf>:

void
fprintf(int fd, const char *fmt, ...)
{
 3e6:	715d                	add	sp,sp,-80
 3e8:	ec06                	sd	ra,24(sp)
 3ea:	e822                	sd	s0,16(sp)
 3ec:	1000                	add	s0,sp,32
 3ee:	e010                	sd	a2,0(s0)
 3f0:	e414                	sd	a3,8(s0)
 3f2:	e818                	sd	a4,16(s0)
 3f4:	ec1c                	sd	a5,24(s0)
 3f6:	03043023          	sd	a6,32(s0)
 3fa:	03143423          	sd	a7,40(s0)
  va_list ap;

  va_start(ap, fmt);
 3fe:	fe843423          	sd	s0,-24(s0)
  vprintf(fd, fmt, ap);
 402:	8622                	mv	a2,s0
 404:	d41ff0ef          	jal	144 <vprintf>
}
 408:	60e2                	ld	ra,24(sp)
 40a:	6442                	ld	s0,16(sp)
 40c:	6161                	add	sp,sp,80
 40e:	8082                	ret

0000000000000410 <printf>:

void
printf(const char *fmt, ...)
{
 410:	711d                	add	sp,sp,-96
 412:	ec06                	sd	ra,24(sp)
 414:	e822                	sd	s0,16(sp)
 416:	1000                	add	s0,sp,32
 418:	e40c                	sd	a1,8(s0)
 41a:	e810                	sd	a2,16(s0)
 41c:	ec14                	sd	a3,24(s0)
 41e:	f018                	sd	a4,32(s0)
 420:	f41c                	sd	a5,40(s0)
 422:	03043823          	sd	a6,48(s0)
 426:	03143c23          	sd	a7,56(s0)
  va_list ap;

  va_start(ap, fmt);
 42a:	00840613          	add	a2,s0,8
 42e:	fec43423          	sd	a2,-24(s0)
  vprintf(1, fmt, ap);
 432:	85aa                	mv	a1,a0
 434:	4505                	li	a0,1
 436:	d0fff0ef          	jal	144 <vprintf>
 43a:	60e2                	ld	ra,24(sp)
 43c:	6442                	ld	s0,16(sp)
 43e:	6125                	add	sp,sp,96
 440:	8082                	ret
