#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"include/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	

entry("hello");
entry("exit");  
entry("fork");
entry("wait");
entry("exec");
entry("dup");
entry("open");
entry("mknod");
entry("write");
entry("read");
entry("close");
entry("getpid");
entry("unlink");
entry("uptime");
entry("set_priority");