
user/_waiter:     file format elf64-littleriscv


Disassembly of section .text:

0000000000000000 <foreverwait>:
#include "include/file.h"
#include "include/fcntl.h"


// 用于处理孤儿进程
void foreverwait(){
   0:	1141                	add	sp,sp,-16
   2:	e406                	sd	ra,8(sp)
   4:	e022                	sd	s0,0(sp)
   6:	0800                	add	s0,sp,16
    for(;;){
        int wpid = wait((int *)0);
   8:	4501                	li	a0,0
   a:	0b8000ef          	jal	c2 <wait>
        if(wpid < 0){
   e:	fe055de3          	bgez	a0,8 <foreverwait+0x8>
            exit(1);
  12:	4505                	li	a0,1
  14:	09e000ef          	jal	b2 <exit>

0000000000000018 <fdinit>:
        }
    }
}

void fdinit(){
  18:	1141                	add	sp,sp,-16
  1a:	e406                	sd	ra,8(sp)
  1c:	e022                	sd	s0,0(sp)
  1e:	0800                	add	s0,sp,16
    
    if(open("console", O_RDWR) < 0){
  20:	4589                	li	a1,2
  22:	00000517          	auipc	a0,0x0
  26:	4ae50513          	add	a0,a0,1198 # 4d0 <printf+0x3c>
  2a:	0b0000ef          	jal	da <open>
  2e:	00054c63          	bltz	a0,46 <fdinit+0x2e>
        // 如果没有console设备 那么创建一个
        mknod("console", CONSOLE, 0);
        open("console", O_RDWR);
    }
    dup(0); // stdout
  32:	4501                	li	a0,0
  34:	09e000ef          	jal	d2 <dup>
    dup(0); // stderr
  38:	4501                	li	a0,0
  3a:	098000ef          	jal	d2 <dup>
}
  3e:	60a2                	ld	ra,8(sp)
  40:	6402                	ld	s0,0(sp)
  42:	0141                	add	sp,sp,16
  44:	8082                	ret
        mknod("console", CONSOLE, 0);
  46:	4601                	li	a2,0
  48:	4585                	li	a1,1
  4a:	00000517          	auipc	a0,0x0
  4e:	48650513          	add	a0,a0,1158 # 4d0 <printf+0x3c>
  52:	090000ef          	jal	e2 <mknod>
        open("console", O_RDWR);
  56:	4589                	li	a1,2
  58:	00000517          	auipc	a0,0x0
  5c:	47850513          	add	a0,a0,1144 # 4d0 <printf+0x3c>
  60:	07a000ef          	jal	da <open>
  64:	b7f9                	j	32 <fdinit+0x1a>

0000000000000066 <main>:



int main(){
  66:	1101                	add	sp,sp,-32
  68:	ec06                	sd	ra,24(sp)
  6a:	e822                	sd	s0,16(sp)
  6c:	1000                	add	s0,sp,32

    fdinit();
  6e:	fabff0ef          	jal	18 <fdinit>


    int pid = fork();
  72:	048000ef          	jal	ba <fork>
    if(pid == 0){
  76:	e105                	bnez	a0,96 <main+0x30>
        exec("filetest", (char *[]){"filetest", 0});
  78:	00000517          	auipc	a0,0x0
  7c:	46050513          	add	a0,a0,1120 # 4d8 <printf+0x44>
  80:	fea43023          	sd	a0,-32(s0)
  84:	fe043423          	sd	zero,-24(s0)
  88:	fe040593          	add	a1,s0,-32
  8c:	03e000ef          	jal	ca <exec>
        exit(1);
  90:	4505                	li	a0,1
  92:	020000ef          	jal	b2 <exit>
    }

    foreverwait();
  96:	f6bff0ef          	jal	0 <foreverwait>

000000000000009a <start>:
#include "include/user.h"


void
start(int argc, char **argv)
{
  9a:	1141                	add	sp,sp,-16
  9c:	e406                	sd	ra,8(sp)
  9e:	e022                	sd	s0,0(sp)
  a0:	0800                	add	s0,sp,16
  int r;
  extern int main(int argc, char **argv);
  r = main(argc, argv);
  a2:	fc5ff0ef          	jal	66 <main>


  exit(r);
  a6:	00c000ef          	jal	b2 <exit>

00000000000000aa <hello>:
# generated by usys.pl - do not edit
#include "include/syscall.h"
.global hello
hello:
 li a7, SYS_hello
  aa:	4885                	li	a7,1
 ecall
  ac:	00000073          	ecall
 ret
  b0:	8082                	ret

00000000000000b2 <exit>:
.global exit
exit:
 li a7, SYS_exit
  b2:	4889                	li	a7,2
 ecall
  b4:	00000073          	ecall
 ret
  b8:	8082                	ret

00000000000000ba <fork>:
.global fork
fork:
 li a7, SYS_fork
  ba:	4891                	li	a7,4
 ecall
  bc:	00000073          	ecall
 ret
  c0:	8082                	ret

00000000000000c2 <wait>:
.global wait
wait:
 li a7, SYS_wait
  c2:	488d                	li	a7,3
 ecall
  c4:	00000073          	ecall
 ret
  c8:	8082                	ret

00000000000000ca <exec>:
.global exec
exec:
 li a7, SYS_exec
  ca:	4895                	li	a7,5
 ecall
  cc:	00000073          	ecall
 ret
  d0:	8082                	ret

00000000000000d2 <dup>:
.global dup
dup:
 li a7, SYS_dup
  d2:	489d                	li	a7,7
 ecall
  d4:	00000073          	ecall
 ret
  d8:	8082                	ret

00000000000000da <open>:
.global open
open:
 li a7, SYS_open
  da:	4899                	li	a7,6
 ecall
  dc:	00000073          	ecall
 ret
  e0:	8082                	ret

00000000000000e2 <mknod>:
.global mknod
mknod:
 li a7, SYS_mknod
  e2:	48a1                	li	a7,8
 ecall
  e4:	00000073          	ecall
 ret
  e8:	8082                	ret

00000000000000ea <write>:
.global write
write:
 li a7, SYS_write
  ea:	48a5                	li	a7,9
 ecall
  ec:	00000073          	ecall
 ret
  f0:	8082                	ret

00000000000000f2 <read>:
.global read
read:
 li a7, SYS_read
  f2:	48a9                	li	a7,10
 ecall
  f4:	00000073          	ecall
 ret
  f8:	8082                	ret

00000000000000fa <close>:
.global close
close:
 li a7, SYS_close
  fa:	48ad                	li	a7,11
 ecall
  fc:	00000073          	ecall
 ret
 100:	8082                	ret

0000000000000102 <getpid>:
.global getpid
getpid:
 li a7, SYS_getpid
 102:	48b1                	li	a7,12
 ecall
 104:	00000073          	ecall
 ret
 108:	8082                	ret

000000000000010a <unlink>:
.global unlink
unlink:
 li a7, SYS_unlink
 10a:	48b5                	li	a7,13
 ecall
 10c:	00000073          	ecall
 ret
 110:	8082                	ret

0000000000000112 <putc>:

static char digits[] = "0123456789ABCDEF";

static void
putc(int fd, char c)
{
 112:	1101                	add	sp,sp,-32
 114:	ec06                	sd	ra,24(sp)
 116:	e822                	sd	s0,16(sp)
 118:	1000                	add	s0,sp,32
 11a:	feb407a3          	sb	a1,-17(s0)
  write(fd, &c, 1);
 11e:	4605                	li	a2,1
 120:	fef40593          	add	a1,s0,-17
 124:	fc7ff0ef          	jal	ea <write>
}
 128:	60e2                	ld	ra,24(sp)
 12a:	6442                	ld	s0,16(sp)
 12c:	6105                	add	sp,sp,32
 12e:	8082                	ret

0000000000000130 <printint>:

static void
printint(int fd, long long xx, int base, int sgn)
{
 130:	715d                	add	sp,sp,-80
 132:	e486                	sd	ra,72(sp)
 134:	e0a2                	sd	s0,64(sp)
 136:	fc26                	sd	s1,56(sp)
 138:	f84a                	sd	s2,48(sp)
 13a:	f44e                	sd	s3,40(sp)
 13c:	0880                	add	s0,sp,80
 13e:	892a                	mv	s2,a0
  char buf[20];
  int i, neg;
  unsigned long long x;

  neg = 0;
  if(sgn && xx < 0){
 140:	c299                	beqz	a3,146 <printint+0x16>
 142:	0605cf63          	bltz	a1,1c0 <printint+0x90>
  neg = 0;
 146:	4881                	li	a7,0
 148:	fb840693          	add	a3,s0,-72
    x = -xx;
  } else {
    x = xx;
  }

  i = 0;
 14c:	4781                	li	a5,0
  do{
    buf[i++] = digits[x % base];
 14e:	4f000513          	li	a0,1264
 152:	883e                	mv	a6,a5
 154:	2785                	addw	a5,a5,1
 156:	02c5f733          	remu	a4,a1,a2
 15a:	972a                	add	a4,a4,a0
 15c:	00074703          	lbu	a4,0(a4)
 160:	00e68023          	sb	a4,0(a3)
  }while((x /= base) != 0);
 164:	872e                	mv	a4,a1
 166:	02c5d5b3          	divu	a1,a1,a2
 16a:	0685                	add	a3,a3,1
 16c:	fec773e3          	bgeu	a4,a2,152 <printint+0x22>
  if(neg)
 170:	00088b63          	beqz	a7,186 <printint+0x56>
    buf[i++] = '-';
 174:	fd078793          	add	a5,a5,-48
 178:	97a2                	add	a5,a5,s0
 17a:	02d00713          	li	a4,45
 17e:	fee78423          	sb	a4,-24(a5)
 182:	0028079b          	addw	a5,a6,2

  while(--i >= 0)
 186:	02f05663          	blez	a5,1b2 <printint+0x82>
 18a:	fb840713          	add	a4,s0,-72
 18e:	00f704b3          	add	s1,a4,a5
 192:	fff70993          	add	s3,a4,-1
 196:	99be                	add	s3,s3,a5
 198:	37fd                	addw	a5,a5,-1
 19a:	1782                	sll	a5,a5,0x20
 19c:	9381                	srl	a5,a5,0x20
 19e:	40f989b3          	sub	s3,s3,a5
    putc(fd, buf[i]);
 1a2:	fff4c583          	lbu	a1,-1(s1)
 1a6:	854a                	mv	a0,s2
 1a8:	f6bff0ef          	jal	112 <putc>
  while(--i >= 0)
 1ac:	14fd                	add	s1,s1,-1
 1ae:	ff349ae3          	bne	s1,s3,1a2 <printint+0x72>
}
 1b2:	60a6                	ld	ra,72(sp)
 1b4:	6406                	ld	s0,64(sp)
 1b6:	74e2                	ld	s1,56(sp)
 1b8:	7942                	ld	s2,48(sp)
 1ba:	79a2                	ld	s3,40(sp)
 1bc:	6161                	add	sp,sp,80
 1be:	8082                	ret
    x = -xx;
 1c0:	40b005b3          	neg	a1,a1
    neg = 1;
 1c4:	4885                	li	a7,1
    x = -xx;
 1c6:	b749                	j	148 <printint+0x18>

00000000000001c8 <vprintf>:
}

// Print to the given fd. Only understands %d, %x, %p, %c, %s.
void
vprintf(int fd, const char *fmt, va_list ap)
{
 1c8:	711d                	add	sp,sp,-96
 1ca:	ec86                	sd	ra,88(sp)
 1cc:	e8a2                	sd	s0,80(sp)
 1ce:	e4a6                	sd	s1,72(sp)
 1d0:	e0ca                	sd	s2,64(sp)
 1d2:	fc4e                	sd	s3,56(sp)
 1d4:	f852                	sd	s4,48(sp)
 1d6:	f456                	sd	s5,40(sp)
 1d8:	f05a                	sd	s6,32(sp)
 1da:	ec5e                	sd	s7,24(sp)
 1dc:	e862                	sd	s8,16(sp)
 1de:	e466                	sd	s9,8(sp)
 1e0:	e06a                	sd	s10,0(sp)
 1e2:	1080                	add	s0,sp,96
  char *s;
  int c0, c1, c2, i, state;

  state = 0;
  for(i = 0; fmt[i]; i++){
 1e4:	0005c903          	lbu	s2,0(a1)
 1e8:	26090363          	beqz	s2,44e <vprintf+0x286>
 1ec:	8b2a                	mv	s6,a0
 1ee:	8a2e                	mv	s4,a1
 1f0:	8bb2                	mv	s7,a2
  state = 0;
 1f2:	4981                	li	s3,0
  for(i = 0; fmt[i]; i++){
 1f4:	4481                	li	s1,0
 1f6:	4701                	li	a4,0
      if(c0 == '%'){
        state = '%';
      } else {
        putc(fd, c0);
      }
    } else if(state == '%'){
 1f8:	02500a93          	li	s5,37
      c1 = c2 = 0;
      if(c0) c1 = fmt[i+1] & 0xff;
      if(c1) c2 = fmt[i+2] & 0xff;
      if(c0 == 'd'){
 1fc:	06400c13          	li	s8,100
        printint(fd, va_arg(ap, int), 10, 1);
      } else if(c0 == 'l' && c1 == 'd'){
 200:	06c00c93          	li	s9,108
 204:	a005                	j	224 <vprintf+0x5c>
        putc(fd, c0);
 206:	85ca                	mv	a1,s2
 208:	855a                	mv	a0,s6
 20a:	f09ff0ef          	jal	112 <putc>
 20e:	a019                	j	214 <vprintf+0x4c>
    } else if(state == '%'){
 210:	03598263          	beq	s3,s5,234 <vprintf+0x6c>
  for(i = 0; fmt[i]; i++){
 214:	2485                	addw	s1,s1,1
 216:	8726                	mv	a4,s1
 218:	009a07b3          	add	a5,s4,s1
 21c:	0007c903          	lbu	s2,0(a5)
 220:	22090763          	beqz	s2,44e <vprintf+0x286>
    c0 = fmt[i] & 0xff;
 224:	0009079b          	sext.w	a5,s2
    if(state == 0){
 228:	fe0994e3          	bnez	s3,210 <vprintf+0x48>
      if(c0 == '%'){
 22c:	fd579de3          	bne	a5,s5,206 <vprintf+0x3e>
        state = '%';
 230:	89be                	mv	s3,a5
 232:	b7cd                	j	214 <vprintf+0x4c>
      if(c0) c1 = fmt[i+1] & 0xff;
 234:	cbc9                	beqz	a5,2c6 <vprintf+0xfe>
 236:	00ea06b3          	add	a3,s4,a4
 23a:	0016c683          	lbu	a3,1(a3)
      c1 = c2 = 0;
 23e:	8636                	mv	a2,a3
      if(c1) c2 = fmt[i+2] & 0xff;
 240:	c681                	beqz	a3,248 <vprintf+0x80>
 242:	9752                	add	a4,a4,s4
 244:	00274603          	lbu	a2,2(a4)
      if(c0 == 'd'){
 248:	05878363          	beq	a5,s8,28e <vprintf+0xc6>
      } else if(c0 == 'l' && c1 == 'd'){
 24c:	05978d63          	beq	a5,s9,2a6 <vprintf+0xde>
        printint(fd, va_arg(ap, uint64), 10, 1);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
        printint(fd, va_arg(ap, uint64), 10, 1);
        i += 2;
      } else if(c0 == 'u'){
 250:	07500713          	li	a4,117
 254:	0ee78763          	beq	a5,a4,342 <vprintf+0x17a>
        printint(fd, va_arg(ap, uint64), 10, 0);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'u'){
        printint(fd, va_arg(ap, uint64), 10, 0);
        i += 2;
      } else if(c0 == 'x'){
 258:	07800713          	li	a4,120
 25c:	12e78963          	beq	a5,a4,38e <vprintf+0x1c6>
        printint(fd, va_arg(ap, uint64), 16, 0);
        i += 1;
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'x'){
        printint(fd, va_arg(ap, uint64), 16, 0);
        i += 2;
      } else if(c0 == 'p'){
 260:	07000713          	li	a4,112
 264:	14e78e63          	beq	a5,a4,3c0 <vprintf+0x1f8>
        printptr(fd, va_arg(ap, uint64));
      } else if(c0 == 'c'){
 268:	06300713          	li	a4,99
 26c:	18e78a63          	beq	a5,a4,400 <vprintf+0x238>
        putc(fd, va_arg(ap, uint32));
      } else if(c0 == 's'){
 270:	07300713          	li	a4,115
 274:	1ae78063          	beq	a5,a4,414 <vprintf+0x24c>
        if((s = va_arg(ap, char*)) == 0)
          s = "(null)";
        for(; *s; s++)
          putc(fd, *s);
      } else if(c0 == '%'){
 278:	02500713          	li	a4,37
 27c:	04e79563          	bne	a5,a4,2c6 <vprintf+0xfe>
        putc(fd, '%');
 280:	02500593          	li	a1,37
 284:	855a                	mv	a0,s6
 286:	e8dff0ef          	jal	112 <putc>
        // Unknown % sequence.  Print it to draw attention.
        putc(fd, '%');
        putc(fd, c0);
      }

      state = 0;
 28a:	4981                	li	s3,0
 28c:	b761                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, int), 10, 1);
 28e:	008b8913          	add	s2,s7,8
 292:	4685                	li	a3,1
 294:	4629                	li	a2,10
 296:	000ba583          	lw	a1,0(s7)
 29a:	855a                	mv	a0,s6
 29c:	e95ff0ef          	jal	130 <printint>
 2a0:	8bca                	mv	s7,s2
      state = 0;
 2a2:	4981                	li	s3,0
 2a4:	bf85                	j	214 <vprintf+0x4c>
      } else if(c0 == 'l' && c1 == 'd'){
 2a6:	06400793          	li	a5,100
 2aa:	02f68963          	beq	a3,a5,2dc <vprintf+0x114>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
 2ae:	06c00793          	li	a5,108
 2b2:	04f68263          	beq	a3,a5,2f6 <vprintf+0x12e>
      } else if(c0 == 'l' && c1 == 'u'){
 2b6:	07500793          	li	a5,117
 2ba:	0af68063          	beq	a3,a5,35a <vprintf+0x192>
      } else if(c0 == 'l' && c1 == 'x'){
 2be:	07800793          	li	a5,120
 2c2:	0ef68263          	beq	a3,a5,3a6 <vprintf+0x1de>
        putc(fd, '%');
 2c6:	02500593          	li	a1,37
 2ca:	855a                	mv	a0,s6
 2cc:	e47ff0ef          	jal	112 <putc>
        putc(fd, c0);
 2d0:	85ca                	mv	a1,s2
 2d2:	855a                	mv	a0,s6
 2d4:	e3fff0ef          	jal	112 <putc>
      state = 0;
 2d8:	4981                	li	s3,0
 2da:	bf2d                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 1);
 2dc:	008b8913          	add	s2,s7,8
 2e0:	4685                	li	a3,1
 2e2:	4629                	li	a2,10
 2e4:	000bb583          	ld	a1,0(s7)
 2e8:	855a                	mv	a0,s6
 2ea:	e47ff0ef          	jal	130 <printint>
        i += 1;
 2ee:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 10, 1);
 2f0:	8bca                	mv	s7,s2
      state = 0;
 2f2:	4981                	li	s3,0
        i += 1;
 2f4:	b705                	j	214 <vprintf+0x4c>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'd'){
 2f6:	06400793          	li	a5,100
 2fa:	02f60763          	beq	a2,a5,328 <vprintf+0x160>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'u'){
 2fe:	07500793          	li	a5,117
 302:	06f60963          	beq	a2,a5,374 <vprintf+0x1ac>
      } else if(c0 == 'l' && c1 == 'l' && c2 == 'x'){
 306:	07800793          	li	a5,120
 30a:	faf61ee3          	bne	a2,a5,2c6 <vprintf+0xfe>
        printint(fd, va_arg(ap, uint64), 16, 0);
 30e:	008b8913          	add	s2,s7,8
 312:	4681                	li	a3,0
 314:	4641                	li	a2,16
 316:	000bb583          	ld	a1,0(s7)
 31a:	855a                	mv	a0,s6
 31c:	e15ff0ef          	jal	130 <printint>
        i += 2;
 320:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 16, 0);
 322:	8bca                	mv	s7,s2
      state = 0;
 324:	4981                	li	s3,0
        i += 2;
 326:	b5fd                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 1);
 328:	008b8913          	add	s2,s7,8
 32c:	4685                	li	a3,1
 32e:	4629                	li	a2,10
 330:	000bb583          	ld	a1,0(s7)
 334:	855a                	mv	a0,s6
 336:	dfbff0ef          	jal	130 <printint>
        i += 2;
 33a:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 10, 1);
 33c:	8bca                	mv	s7,s2
      state = 0;
 33e:	4981                	li	s3,0
        i += 2;
 340:	bdd1                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint32), 10, 0);
 342:	008b8913          	add	s2,s7,8
 346:	4681                	li	a3,0
 348:	4629                	li	a2,10
 34a:	000be583          	lwu	a1,0(s7)
 34e:	855a                	mv	a0,s6
 350:	de1ff0ef          	jal	130 <printint>
 354:	8bca                	mv	s7,s2
      state = 0;
 356:	4981                	li	s3,0
 358:	bd75                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 0);
 35a:	008b8913          	add	s2,s7,8
 35e:	4681                	li	a3,0
 360:	4629                	li	a2,10
 362:	000bb583          	ld	a1,0(s7)
 366:	855a                	mv	a0,s6
 368:	dc9ff0ef          	jal	130 <printint>
        i += 1;
 36c:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 10, 0);
 36e:	8bca                	mv	s7,s2
      state = 0;
 370:	4981                	li	s3,0
        i += 1;
 372:	b54d                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 10, 0);
 374:	008b8913          	add	s2,s7,8
 378:	4681                	li	a3,0
 37a:	4629                	li	a2,10
 37c:	000bb583          	ld	a1,0(s7)
 380:	855a                	mv	a0,s6
 382:	dafff0ef          	jal	130 <printint>
        i += 2;
 386:	2489                	addw	s1,s1,2
        printint(fd, va_arg(ap, uint64), 10, 0);
 388:	8bca                	mv	s7,s2
      state = 0;
 38a:	4981                	li	s3,0
        i += 2;
 38c:	b561                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint32), 16, 0);
 38e:	008b8913          	add	s2,s7,8
 392:	4681                	li	a3,0
 394:	4641                	li	a2,16
 396:	000be583          	lwu	a1,0(s7)
 39a:	855a                	mv	a0,s6
 39c:	d95ff0ef          	jal	130 <printint>
 3a0:	8bca                	mv	s7,s2
      state = 0;
 3a2:	4981                	li	s3,0
 3a4:	bd85                	j	214 <vprintf+0x4c>
        printint(fd, va_arg(ap, uint64), 16, 0);
 3a6:	008b8913          	add	s2,s7,8
 3aa:	4681                	li	a3,0
 3ac:	4641                	li	a2,16
 3ae:	000bb583          	ld	a1,0(s7)
 3b2:	855a                	mv	a0,s6
 3b4:	d7dff0ef          	jal	130 <printint>
        i += 1;
 3b8:	2485                	addw	s1,s1,1
        printint(fd, va_arg(ap, uint64), 16, 0);
 3ba:	8bca                	mv	s7,s2
      state = 0;
 3bc:	4981                	li	s3,0
        i += 1;
 3be:	bd99                	j	214 <vprintf+0x4c>
        printptr(fd, va_arg(ap, uint64));
 3c0:	008b8d13          	add	s10,s7,8
 3c4:	000bb983          	ld	s3,0(s7)
  putc(fd, '0');
 3c8:	03000593          	li	a1,48
 3cc:	855a                	mv	a0,s6
 3ce:	d45ff0ef          	jal	112 <putc>
  putc(fd, 'x');
 3d2:	07800593          	li	a1,120
 3d6:	855a                	mv	a0,s6
 3d8:	d3bff0ef          	jal	112 <putc>
 3dc:	4941                	li	s2,16
    putc(fd, digits[x >> (sizeof(uint64) * 8 - 4)]);
 3de:	4f000b93          	li	s7,1264
 3e2:	03c9d793          	srl	a5,s3,0x3c
 3e6:	97de                	add	a5,a5,s7
 3e8:	0007c583          	lbu	a1,0(a5)
 3ec:	855a                	mv	a0,s6
 3ee:	d25ff0ef          	jal	112 <putc>
  for (i = 0; i < (sizeof(uint64) * 2); i++, x <<= 4)
 3f2:	0992                	sll	s3,s3,0x4
 3f4:	397d                	addw	s2,s2,-1
 3f6:	fe0916e3          	bnez	s2,3e2 <vprintf+0x21a>
        printptr(fd, va_arg(ap, uint64));
 3fa:	8bea                	mv	s7,s10
      state = 0;
 3fc:	4981                	li	s3,0
 3fe:	bd19                	j	214 <vprintf+0x4c>
        putc(fd, va_arg(ap, uint32));
 400:	008b8913          	add	s2,s7,8
 404:	000bc583          	lbu	a1,0(s7)
 408:	855a                	mv	a0,s6
 40a:	d09ff0ef          	jal	112 <putc>
 40e:	8bca                	mv	s7,s2
      state = 0;
 410:	4981                	li	s3,0
 412:	b509                	j	214 <vprintf+0x4c>
        if((s = va_arg(ap, char*)) == 0)
 414:	008b8993          	add	s3,s7,8
 418:	000bb903          	ld	s2,0(s7)
 41c:	00090f63          	beqz	s2,43a <vprintf+0x272>
        for(; *s; s++)
 420:	00094583          	lbu	a1,0(s2)
 424:	c195                	beqz	a1,448 <vprintf+0x280>
          putc(fd, *s);
 426:	855a                	mv	a0,s6
 428:	cebff0ef          	jal	112 <putc>
        for(; *s; s++)
 42c:	0905                	add	s2,s2,1
 42e:	00094583          	lbu	a1,0(s2)
 432:	f9f5                	bnez	a1,426 <vprintf+0x25e>
        if((s = va_arg(ap, char*)) == 0)
 434:	8bce                	mv	s7,s3
      state = 0;
 436:	4981                	li	s3,0
 438:	bbf1                	j	214 <vprintf+0x4c>
          s = "(null)";
 43a:	00000917          	auipc	s2,0x0
 43e:	0ae90913          	add	s2,s2,174 # 4e8 <printf+0x54>
        for(; *s; s++)
 442:	02800593          	li	a1,40
 446:	b7c5                	j	426 <vprintf+0x25e>
        if((s = va_arg(ap, char*)) == 0)
 448:	8bce                	mv	s7,s3
      state = 0;
 44a:	4981                	li	s3,0
 44c:	b3e1                	j	214 <vprintf+0x4c>
    }
  }
}
 44e:	60e6                	ld	ra,88(sp)
 450:	6446                	ld	s0,80(sp)
 452:	64a6                	ld	s1,72(sp)
 454:	6906                	ld	s2,64(sp)
 456:	79e2                	ld	s3,56(sp)
 458:	7a42                	ld	s4,48(sp)
 45a:	7aa2                	ld	s5,40(sp)
 45c:	7b02                	ld	s6,32(sp)
 45e:	6be2                	ld	s7,24(sp)
 460:	6c42                	ld	s8,16(sp)
 462:	6ca2                	ld	s9,8(sp)
 464:	6d02                	ld	s10,0(sp)
 466:	6125                	add	sp,sp,96
 468:	8082                	ret

000000000000046a <fprintf>:

void
fprintf(int fd, const char *fmt, ...)
{
 46a:	715d                	add	sp,sp,-80
 46c:	ec06                	sd	ra,24(sp)
 46e:	e822                	sd	s0,16(sp)
 470:	1000                	add	s0,sp,32
 472:	e010                	sd	a2,0(s0)
 474:	e414                	sd	a3,8(s0)
 476:	e818                	sd	a4,16(s0)
 478:	ec1c                	sd	a5,24(s0)
 47a:	03043023          	sd	a6,32(s0)
 47e:	03143423          	sd	a7,40(s0)
  va_list ap;

  va_start(ap, fmt);
 482:	fe843423          	sd	s0,-24(s0)
  vprintf(fd, fmt, ap);
 486:	8622                	mv	a2,s0
 488:	d41ff0ef          	jal	1c8 <vprintf>
}
 48c:	60e2                	ld	ra,24(sp)
 48e:	6442                	ld	s0,16(sp)
 490:	6161                	add	sp,sp,80
 492:	8082                	ret

0000000000000494 <printf>:

void
printf(const char *fmt, ...)
{
 494:	711d                	add	sp,sp,-96
 496:	ec06                	sd	ra,24(sp)
 498:	e822                	sd	s0,16(sp)
 49a:	1000                	add	s0,sp,32
 49c:	e40c                	sd	a1,8(s0)
 49e:	e810                	sd	a2,16(s0)
 4a0:	ec14                	sd	a3,24(s0)
 4a2:	f018                	sd	a4,32(s0)
 4a4:	f41c                	sd	a5,40(s0)
 4a6:	03043823          	sd	a6,48(s0)
 4aa:	03143c23          	sd	a7,56(s0)
  va_list ap;

  va_start(ap, fmt);
 4ae:	00840613          	add	a2,s0,8
 4b2:	fec43423          	sd	a2,-24(s0)
  vprintf(1, fmt, ap);
 4b6:	85aa                	mv	a1,a0
 4b8:	4505                	li	a0,1
 4ba:	d0fff0ef          	jal	1c8 <vprintf>
 4be:	60e2                	ld	ra,24(sp)
 4c0:	6442                	ld	s0,16(sp)
 4c2:	6125                	add	sp,sp,96
 4c4:	8082                	ret
